services:
  oracle:
    image: gvenzl/oracle-free
    container_name: oracle_free
    environment:
      ORACLE_PASSWORD: rest123
      APP_USER: rest_with_spring_boot
      APP_USER_PASSWORD: rest123
    ports:
      - "1522:1521"   # host 1522, container 1521

  api:
    build: .
    container_name: spring_api
    depends_on:
      - oracle
    ports:
      - "8081:8080"   # host 8081, container 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: rest_with_spring_boot
      SPRING_DATASOURCE_PASSWORD: rest123















