spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: rest_with_spring_boot
    password: rest123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update   #none
    show-sql: true
    open-in-view: false

  logging:
    level:
      br.com.ana: DEBUG

  spring-doc:
    paths-to-match: /api/**/**
    swagger-ui:
      use-root-path: true