spring:
  profiles:
    active: oracle

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% das requisições (ambiente local)

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      enabled: true

logging:
  level:
    root: INFO

logstash:
  enabled: false
  host: localhost
  port: 5044
