input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  # por enquanto, sem filtros
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
